### ISSUE TITLE
Colons should be part of the word when followed by letters, preceded by non-whitespace

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#10]
Examples:

ráhkistan:  - NOT part of the word
234:t  - PART of the word
234:at - misspelling, PART of the word (correct form above)
NATO:s - PART of the word

<img width="195" alt="skjermbilde 2015-11-19 kl 16 58 07" src="https://cloud.githubusercontent.com/assets/1255285/11426500/5c6a0dc8-9465-11e5-89ec-77ffa195dc05.png">

**Comment by TinoDidriksen** [comment]
Mostly fixed in r85 (commit 931c5da5ab0a67558b597eb5510c8ad48fd614c3) by adding colon to the usable character list. This does mean colon will show in suggestions, but should be rare enough that it doesn't matter.
