### ISSUE TITLE
Misspellings in all uppercase get unexpected suggestions

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#11]
Example (none of the suggestions are reasonable corrections):

<img width="306" alt="skjermbilde 2015-11-19 kl 16 53 43" src="https://cloud.githubusercontent.com/assets/1255285/11426600/e7bfb170-9465-11e5-804e-5858e1d348e6.png">

Here is the same input with initial cap (second and third suggestions are reasonable corrections):

![skjermbilde 2015-11-25 kl 12 54 24](https://cloud.githubusercontent.com/assets/1255285/11426660/39e7b06a-9466-11e5-97cd-71d942a882d0.png)

And the same input with all lowercase (all suggestions are reasonable corrections):

![skjermbilde 2015-11-25 kl 12 53 23](https://cloud.githubusercontent.com/assets/1255285/11426648/2314758a-9466-11e5-8cef-fd65e1873e78.png)

It might be that this can all be corrected in the fst by giving higher weights to certain types of compounds. As for now, one of the uppercase only suggestions is analysed as follows:

```
$ echo Kant-RV-irgi | hfst-lookup -q build/newspellers/tools/spellcheckers/fstbased/analyser-fstspeller-gt-norm.hfst 
Kant-RV-irgi    Kant+N+Prop+Sem/Sur+Cmp-#RV+N+ACR+Cmp-#irgi+N+Sg+Nom    17,031221
Kant-RV-irgi    Kant+N+Prop+Sem/Sur+Cmp-#RV+N+ACR+Cmp-#irgi+N+Sg+Nom    10017,031250
```

Giving higher weight to +ACR tags should help improve the suggestions. I'll try this first.

**Comment by snomos** [comment]
Adding more weight did not really change anything. Is there anything that can be done to the case handling algorithm to improve suggestions in these cases?

**Comment by snomos** [comment]
Given suggestion vs expected suggestion:

```
$ echo Kant-RV-irgi | hfst-lookup -q fstbased/analyser-fstspeller-gt-norm.hfst 
Kant-RV-irgi    Kant+N+Prop+Sem/Sur+Cmp-#RV+N+ACR+Cmp-#irgi+N+Sg+Nom    517,031250
Kant-RV-irgi    Kant+N+Prop+Sem/Sur+Cmp-#RV+N+ACR+Cmp-#irgi+N+Sg+Nom    10517,031250

$ echo kánturvirgi | hfst-lookup -q fstbased/analyser-fstspeller-gt-norm.hfst 
kánturvirgi    kantuvra+N+Cmp#virgi+N+Sg+Nom   15,031221
```

Note the weight differences.

**Comment by TinoDidriksen** [comment]
Fixed in hfst-ospell r4554. It actually worked as expected if you just asked for suggestions right away, but the caching of non-suggestion lookups broke it.
