### ISSUE TITLE
All uppercase names are flagged as misspelled, suggestions rejected when inserted

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#12]
When the option to check the spelling of all uppercase strings is on, (inflected) names are flagged as misspelled, where as the same string in regular / lexical case is not flagged:

![skjermbilde 2015-12-03 kl 11 05 34](https://cloud.githubusercontent.com/assets/1255285/11556196/d15dbd58-99ad-11e5-8c29-c02138520c1f.png)
- regular case vs all-upper: see Kautokeino
- inflected vs base form: OSLO vs most others - but KAUTOKEINO is also a base form, so the pattern is not fully consistent
- names vs non-names: ráidočiekčan vs RÁIDOČIEKČAN vs KAUTOKEINO - only the last one is flagged

Further, when introducing a misspelling in one of the all-upper names, the correct form is suggested, but when inserted, it is still flagged as misspelled:

![skjermbilde 2015-12-03 kl 10 54 32](https://cloud.githubusercontent.com/assets/1255285/11556292/5b864f68-99ae-11e5-83a9-a0bc79d1d1ab.png)

That is, it rejects its own suggestions in these cases.

**Comment by TinoDidriksen** [comment]
Fixed in hfst-ospell r4561.
