### ISSUE TITLE
North Sami has no version info easter egg

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#13]
All our spellers are automatically equipped with an easter egg giving core version information, triggered by asking for suggestions to the string "nuvviDspeller". This is what it looks like for South Sami:

![skjermbilde 2015-12-03 kl 10 58 52](https://cloud.githubusercontent.com/assets/1255285/11556374/db2585b8-99ae-11e5-83a0-40e42c41a124.png)

The North Sami spellers from this week has been lacking the easter egg, although when building and testing on my own computer it is there. The North Sami Word / MS Office speller gives the following list of suggestions:

![skjermbilde 2015-12-03 kl 10 58 19](https://cloud.githubusercontent.com/assets/1255285/11556428/28f4b8b8-99af-11e5-83af-4e4ac489ef33.png)

These suggestions all have a much higher weight than the easter egg suggestions. Thus, it looks to me as the easter egg was not built for some reason for SME.

Having the possibility to identify the lexicon version is quite important when debugging user error messages - often it turns out that they have an old speller, and that can easily be identified by asking them to type in the easter egg trigger.

**Comment by TinoDidriksen** [comment]
Fixed in hfst-ospell r4560
