### ISSUE TITLE
Word crashing after a period of heavy use with North Sámi speller

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#18]
Background:
1. User installed the newest divvun package (divvun.no)
2. User edited North Sámi texts for one day, everything worked fine
3. User continued the next day, Word hangs (does not respond) and needs to be forced down
4. User uninstalled the divvun tools, and Word behaves as normal again

OS: windows 7 enterprise service pack 1, 64 bit
Word: Microsoft Office Professional Plus 2013, 32 bit

Problem trigging document sent via e-mail for privacy & copyright reasons.

**Comment by TinoDidriksen** [comment]
"continued the next day" as in left Word open for the night, or through computer sleep/hibernate, or what? 'cause the document as-is loads and operates fine for me - can't see any errors or hangs.

**Comment by albbas** [comment]
Another user reports that Outlook 2013 hangs, both on Windows 8.1 and 10. The hang mostly happens when switching from Norwegian to Saami keyboard layout (using Windows + Space keys). After uninstalling the newest divvun tools, it works normally.

**Comment by albbas** [comment]
Using this file as input: https://gtsvn.uit.no/biggies/trunk/prooftesting/smj/hfst-mso/goldstandard.spin.txt

I see this on my Linux machine:
hfst-mso $ hfst-ospell-office smj-latest/smj.zhfst < goldstandard.spin.txt > boerre.spout.txt
**\* Error in `hfst-ospell-office': munmap_chunk(): invalid pointer: 0x0000000000c11880 ***
Aborted (core dumped)

$ hfst-ospell --version

hfstospell 0.3.1
Jan 14 2016 11:18:07
copyright (C) 2009 - 2014 University of Helsinki

The crash occurs when the spelling is done, ie. all input words get a suggestion.

**Comment by albbas** [comment]
Every line in https://gtsvn.uit.no/biggies/trunk/prooftesting/smj/hfst-mso/goldstandard.spin.txt starts with "5 ". I removed those, and used hfst-ospell: 
hfst-mso $ hfst-ospell smj-latest/smj.zhfst < goldstandard.spin.txt > boerre.spout.txt

hfst-ospell did not crash on this input.

**Comment by TinoDidriksen** [comment]
The initial number is how many suggestions to generate. If a line doesn't start with a number, it is discarded entirely. If you want to test no suggestions, replace them with 0.

Sounds like I need to add in a check for whether the backend is still alive, and maybe restart it after X thousand lookups. Which is totally doable and why I preferred to split it into a separate process.

**Comment by TinoDidriksen** [comment]
Fixed in r90 (5e7cd8aa4fe9dfddb198a00e505d82d2ec4c94b3), and all speller packages have been regenerated.

The frontend will now query status of backend and restart it if needed, and will also use async I/O with a wait of 7 seconds before declaring the operation a failure.
