### ISSUE TITLE
hfst-ospell-office dumps core on [uppercase-char] and {uppercase-char}

### ISSUE THREAD

**Issue by albbas** [TinoDidriksen/spellers#19]
Examples from commandline use:
hfst-mso $ echo "5 [L]" | /usr/local/bin/hfst-ospell-office se-latest/se.zhfst
@@ hfst-ospell-office is alive
*
**\* Error in `/usr/local/bin/hfst-ospell-office': munmap_chunk(): invalid pointer: 0x000000000236e880 ***
Aborted (core dumped)

hfst-mso $ echo "5 [l]" | /usr/local/bin/hfst-ospell-office se-latest/se.zhfst
@@ hfst-ospell-office is alive
*

{L}, {L], [L} also results in core dumps.

hfst-mso $ /usr/local/bin/hfst-ospell --version

hfstospell 0.4.0
Jan 26 2016 10:02:10
copyright (C) 2009 - 2016 University of Helsinki

The original input had about 90000 lines, one "word" on each line.
On Linux hfst-ospell-office dumps core _after_ all lines have been spell checked, on OS X it crashes more randomly (somewhere in the middle of the process).

**Comment by albbas** [comment]
hfst-ospell does not have this behaviour:
hfst-mso $ echo "{l]" | /usr/local/bin/hfst-ospell --limit=5 se-latest/se.zhfst
"{l]" is NOT in the lexicon:
hfst-mso $ echo "{L]" | /usr/local/bin/hfst-ospell --limit=5 se-latest/se.zhfst
"{L]" is NOT in the lexicon:
hfst-mso $

**Comment by TinoDidriksen** [comment]
Fixed in hfst-ospell r4638. I'll regenerate speller packages when it's done building for all platforms.
