### ISSUE TITLE
A single space will trigger a red underline

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#2]
A single space surrounded by linebreaks (U+000A) will trigger a red underline in MS Word using the SME speller from today. To repeat, insert the following in a document (here given as Unicode HEX code points to avoid misunderstandings and code garbling):

U+000A
U+000A
U+0020
U+000A
U+000A

Set the text to North Sami. Notice how there is a very short squiggly red line where the space is.

**Comment by snomos** [comment]
This is true also if the space is followed by other space characters and text, see screenshot:
<img width="95" alt="skjermbilde 2015-10-19 kl 09 46 31" src="https://cloud.githubusercontent.com/assets/1255285/10571283/758bf678-7646-11e5-9ffc-ef0652c4a86a.png">

**Comment by TinoDidriksen** [comment]
Should be fixed in latest versions at http://apertium.projectjj.com/spellers/

**Comment by snomos** [comment]
Just to confirm that the latest nightly build has fixed this.
