### ISSUE TITLE
Installing the msoffice speller on a Windows terminal server does not make it available for all users.

### ISSUE THREAD

**Issue by albbas** [TinoDidriksen/spellers#23]
Only the admin user that installed the speller has access to it.

**Comment by TinoDidriksen** [comment]
Really? Works locally, so why should terminal server be different. I create a `HKLM\Software\Microsoft\Active Setup\Installed Components` key to automatically run the `create-hkcu.exe` tool when a user logs in that hasn't run it before. This doesn't do anything under TS?

**Comment by albbas** [comment]
It turned out that policy hindered `create-hkcu.exe` from running on the TS. When that policy was relaxed, the problem was solved.
