### ISSUE TITLE
Forward slash counted as part of the word

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#5]
In a string like Sállan/Glimt, the forward slash is counted as part of the word, when it should not:

<img width="220" alt="skjermbilde 2015-11-16 kl 13 38 28" src="https://cloud.githubusercontent.com/assets/1255285/11183215/ccbd18d8-8c70-11e5-957a-96512f0ebce6.png">

Each of the two parts before and after the slash should be treated as independent words, ie the slash should not be considered a word character. This could be language specific, such that some languages want it as part of their words, and others not, although I am not aware of any such language on first thought.

**Comment by TinoDidriksen** [comment]
Should be fixed in r82 (commit 7a95ed59466b8adaef89c398e19bb39ae3ff3c58) along with NBSP and punctuation, and thus next nightly rebuild.
