### ISSUE TITLE
Keep initial upper case in suggestions

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#6]
When a misspelled word starts with a capital letter, also the suggestions should be with an initial capital letter. This is presently not the case:

<img width="296" alt="skjermbilde 2015-11-16 kl 13 34 45" src="https://cloud.githubusercontent.com/assets/1255285/11183372/95bde438-8c71-11e5-8478-9757aec46ad0.png">

Unnaraččas should have been corrected to Unnoraččas.

Tested with the 16.11.2015 version.

**Comment by TinoDidriksen** [comment]
Fixed in hfst-ospell r4542, https://sourceforge.net/p/hfst/code/4542/
