### ISSUE TITLE
Punctuation should not be part of suggestions

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#7]
Comma is treated as part of the word as well as the suggestions. This bug does not in itself create bad input or output, but it does increase the noise level of the suggestions:

<img width="296" alt="skjermbilde 2015-11-16 kl 13 34 45" src="https://cloud.githubusercontent.com/assets/1255285/11195363/e19a2548-8cb1-11e5-957e-d62102d6d06b.png">

It would be better to not include the comma in the input, and thus also remove it from the suggestions.

**Comment by TinoDidriksen** [comment]
Should be fixed in r82 (commit 7a95ed59466b8adaef89c398e19bb39ae3ff3c58) along with NBSP and punctuation, and thus next nightly rebuild.
