### ISSUE TITLE
Hyphens should always be part of the word

### ISSUE THREAD

**Issue by snomos** [TinoDidriksen/spellers#9]
At least in the Sami languages. This is true for all positions (initial, middle, final):
-davvi
el-rávdnje
dutki-

Screenshots demonstrating how it is now, and how this leads to irrelevant suggestions:

<img width="214" alt="skjermbilde 2015-11-19 kl 17 03 12" src="https://cloud.githubusercontent.com/assets/1255285/11426339/fc60f3de-9463-11e5-9d12-21f420bfd163.png">

<img width="308" alt="skjermbilde 2015-11-19 kl 17 04 09" src="https://cloud.githubusercontent.com/assets/1255285/11426359/3a74c07e-9464-11e5-8d0c-51212b2e49c6.png">

<img width="201" alt="skjermbilde 2015-11-19 kl 17 04 50" src="https://cloud.githubusercontent.com/assets/1255285/11426360/405604ee-9464-11e5-8fd0-09e96e9a9d92.png">

In all these cases the whole string «el-rávdnje» etc should be the input, and suggestions should be generated from that.

Whether a hyphen is part of a word or not is definitely language dependent. E.g. in English it is probably best to treat the hyphen as a NON-word char (ie a word separator), whereas for Sámi, Norwegian and most other Nordic languages it should be a word character. The only exception to this is when it is used alone, ie with whitechars on each side.

Our Sámi fst's are built with this in mind, and should be able to handle all correct uses of hyphens.

**Comment by TinoDidriksen** [comment]
Fixed in r85 (commit 931c5da5ab0a67558b597eb5510c8ad48fd614c3) by adding these to the usable character list:
- U+002D hyphen-minus
- U+2010 hyphen
- U+2011 non-breaking hyphen
- U+2012 figure dash
- U+2013 en dash
